version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: organisasi_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: keuangan_organisasi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: organisasi_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: fajar@organisasi.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "5050:80"
    depends_on:
      - postgres_db

volumes:
  pgdata: